{{- if .Values.global.ConfigMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.ConfigMap.name | default ( include "Platform.fullname" .)}}

data:
  jwt-Audience: {{ .Values.global.ConfigMap.data.jwtAudience | quote }}
  jwt-Issuer: {{ .Values.global.ConfigMap.data.jwtIssuer | quote }}
  jwt-Expire: {{ .Values.global.ConfigMap.data.jwtExpire | quote}}
  email-config-Email: {{ .Values.global.ConfigMap.data.Email | quote}}
  
{{- end }}