
nameOverride: "recomind-company"
fullnameOverride: "recomind-company"

replicaCount: 2

image:
  repository: redasaad1234/backend-companyservice
  tag: latest
  pullPolicy: IfNotPresent

volumeMounts:
  - name: secrets-store
    mountPath: "/mnt/secrets"
    readOnly: true

volumes:
  - name: secrets-store
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: app-secrets


virtualService:
  enabled: true

service:
  name: company-svc
  type: ClusterIP
  http:
    name: http
    port: 8007
    protocol: http
  grpc:
    name: grpc
    port: 5007
    protocol: h2c

destinationRule:
  enabled: true
  tls:
    mode: ISTIO_MUTUAL
  loadBalancer: ROUND_ROBIN
  h2UpgradePolicy: UPGRADE

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  - name: jwt__Audience
    valueFrom:
      configMapKeyRef:
        name: recomind-config
        key: jwt-Audience
  - name: jwt__Issuers
    valueFrom:
      configMapKeyRef:
        name: recomind-config
        key: jwt-Issuer
  - name: jwt__Expire  
    valueFrom:
      configMapKeyRef:
        name: recomind-config
        key: jwt-Expire

  - name: JwtOptions__SecretKey
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: Jwt-SecretKey
  - name: ConnectionStrings__ProdcutionConnection_Company
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: ProductionConnectionString-Company
        
  - name: Kestrel__Endpoints__Http__Url
    value: "http://0.0.0.0:8007"
  - name: Kestrel__Endpoints__Http__Protocols
    value: "Http1"

  # إعداد منفذ الـ gRPC (بدون TLS)
  - name: Kestrel__Endpoints__Grpc__Url
    value: "http://0.0.0.0:5007"
  - name: Kestrel__Endpoints__Grpc__Protocols
    value: "Http2"