---
# vars file for Roles
docker_registry: redasaad1234/backend

expose_Ports: 8000

domain_name: api.recomind.site

active_services: "{{ services }}"



services:
  - name: authenticationservice
    port: 8082
    volumes:
      - ./Auth/StaticFiles:/app/RecoMindAuthenticationAPI/StaticFiles/Images
    expose_to_nginx: true
    nginx_path: /api/Authentication
    env:
      - .env
      

  - name: databasesettingservice
    port: 8083
    expose_to_nginx: true
    nginx_path: /api/databasesetting
    env:
      - .env


  - name: subscriptionservice
    port: 8084
    expose_to_nginx: true
    nginx_path: /api/subscription
    env:
      - .env


  - name: planeservice
    port: 8085
    expose_to_nginx: true
    nginx_path: /api/plane
    env:
      - .env

  - name: invitationservice
    port: 8086
    expose_to_nginx: true
    nginx_path: /api/invitation
    env:
      - .env

  - name: companyservice
    port: 8088
    expose_to_nginx: true
    nginx_path: /api/company
    env:
      - .env


  - name: reportservice
    port: 8089
    expose_to_nginx: true
    nginx_path: /api/report
    env:
      - .env

  # - name: feedbackservice
  #   port: 8090
  #   expose_to_nginx: true
  #   nginx_path: /api/feedback
  #   env:
  #     - .env

  - name: chatbotservice
    port: 8091
    expose_to_nginx: true
    nginx_path: /api/chatbot
    env:
      - .env

  - name: teamservice
    port: 8093
    
    expose_to_nginx: true
    nginx_path: /api/team
    env:
      - .env