services:
  
  # Service 1: The Redis Queue
  redis:
    image: redis:7-alpine
    container_name: recomind-redis
    hostname: recomind-redis
    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

  # Service 2: The FastAPI API
  data_embedding_api:
    image: hossamtaha9/recomind-ai-vector-data_embedding:latest
    container_name: recomind-ingestion-api
    env_file:
      - .env  # Load all secrets from .env file
    ports:
      - "8000:8000"
    depends_on:
      - redis
    dns:
      - 8.8.8.8
    # --- [MODIFICATION END] ---

  # Service 3: The Celery Worker
  data_impedding_worker:
    image: hossamtaha9/recomind-ai-vector-data_embedding:latest
    container_name: recomind-ingestion-worker
    command: celery -A celery_worker.celery_app worker --loglevel=info -P gevent
    env_file:
      - .env  # The worker also needs all the secrets
    depends_on:
      - redis
    dns:
      - 8.8.8.8
    # --- [MODIFICATION END] ---

  # Service 4: Reporting System
  reporting_system_api:
    image: hossamtaha9/recomind-ai-vector-reporting_system:latest
    container_name: recomind-reporting-system
    env_file:
      - .env  # Load all secrets from .env file
    ports:
      - "8001:8000"
    environment:
      - OPENAI_API_KEY=${OPENROUTER_API_KEY}
      - OPENAI_API_BASE=${BASE_URL}
      - OPENAI_MODEL_NAME=${crewai_LLM_MODEL} 
    depends_on:
      - redis
    dns:
      - 8.8.8.8


  # worker service for reporting system
  reporting_system_worker:
    image: hossamtaha9/recomind-ai-vector-reporting_system:latest
    container_name: recomind-reporting-system-worker
    command: celery -A celery_worker.celery_app worker --loglevel=info -P gevent
    env_file:
      - .env  # The worker also needs all the secrets
    depends_on:
      - redis
      - reporting_system_api

volumes:
  redis_data:
    
  