apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
spec:
  serviceName: {{ .Chart.Name }}-svc
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.StatefulSet.image.repo }}
        ports:
        - name: amqp
          containerPort: {{ .Values.StatefulSet.image.port }}
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        {{- toYaml .Values.StatefulSet.volumeClaimTemplates.accessModes | nindent 8 }}
      resources:
        requests:
          storage: {{ .Values.StatefulSet.volumeClaimTemplates.storage }}
  {{- with .Values.volumes }}
  volumes:
    {{- toYaml . | nindent 4 }}
  {{- end }}