---
# tasks file for Roles


# # install Docker 
# - name: Install Docker on VM
#   import_tasks: templatesTasks/Docker.yml

# setup nginx
- name: Setup Nginx on VM
  import_tasks: templatesTasks/nginx-confg.yml

