
nameOverride: "recomind"
fullnameOverride: "recomind"
global:
  imagePullSecrets:
    - name: registry-secret
  ConfigMap:
    enabled: true
    name: recomind-config
    data:
      jwtAudience: "https://api.recomind.site/"
      jwtIssuer: "https://api.recomind.site/"  
      jwtExpire: "2"
  ingress:
    enabled: true
    className: "nginx"
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      # إضافة السطر التالي للتأكد من تمرير المسار كما هو
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: api.recomind.site
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-svc
                port:
                  number: 8011

          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-svc
                port:
                  number: 5011
    
    

    tls: 
      - hosts:
        - api.recomind.site
        secretName: recomind-tls

PVC:
  enabled: true
  name: recomind-pvc
  storageClassName: recomindstorageclass
  accessModes:
    - ReadWriteOnce
  storage: 2Gi

StorageClass:
  enabled: true
  name: recomindstorageclass
  provisioner: kubernetes.io/no-provisioner
  volumeBindingMode: WaitForFirstConsumer
  parameters:
  reclaimPolicy: Retain

ClusterIssuer:
  enabled: true
  name: letsencrypt-prod
  server: https://acme-v02.api.letsencrypt.org/directory
  email: redasaad010260@gmail.com
  class: nginx





