
nameOverride: "recomind"
fullnameOverride: "recomind"
global:
  imagePullSecrets:
    - name: dockerhub-secret

  
  ConfigMap:
    enabled: true
    name: recomind-config
    data:
      jwtAudience: "https://api.recomind.site/"
      jwtIssuer: "https://api.recomind.site/"  
      jwtExpire: "2"
  ingress:
    enabled: true
    className: "nginx"
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$3
      # إضافة السطر التالي للتأكد من تمرير المسار كما هو
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: api.recomind.site
        paths:
          - path: /api/(auth|users|Authentication)(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-svc
                port:
                  number: 8011

          - path: /api/chatbot(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: chatbot-svc
                port:
                  number: 8009

          - path: /api/comment(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: comment-svc
                port:
                  number: 8012

          - path: /api/Companies(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: company-svc
                port:
                  number: 8007

          - path: /api/Invitation(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: invitation-svc
                port:
                  number: 8006

          - path: /api/Plan(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: plan-svc
                port:
                  number: 8005


          - path: /api/Report(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: report-svc
                port:
                  number: 8008

          - path: /api/Subscription(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: subscription-svc
                port:
                  number: 8004


          - path: /api/(tasks|user-tasks)(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: task-svc
                port:
                  number: 8013

          - path: /api/Team(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: team-svc
                port:
                  number: 8010

          - path: /api/Notification(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: notification-svc
                port:
                  number: 8015

          - path: /api/Mapping(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mapping-svc
                port:
                  number: 8016

          - path: /api/DbSetting(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: database-settings-svc
                port:
                  number: 8003
          
    
    

    tls: 
      - hosts:
        - api.recomind.site
        secretName: recomind-tls-final-aks

PVC:
  enabled: true
  name: recomind-pvc
  storageClassName: recomindstorageclass
  accessModes:
    - ReadWriteOnce
  storage: 2Gi

StorageClass:
  enabled: true
  name: recomindstorageclass
  provisioner: kubernetes.io/no-provisioner
  volumeBindingMode: WaitForFirstConsumer
  parameters:
  reclaimPolicy: Retain

ClusterIssuer:
  enabled: false
  name: letsencrypt-prod
  server: https://acme-v02.api.letsencrypt.org/directory
  email: redasaad010260@gmail.com
  class: nginx





