nameOverride: "rabbitmq"
fullnameOverride: "rabbitmq"

StatefulSet:
  
  image:
    repo: rabbitmq:4.0-management-alpine
    port: 15672
  volumeMounts:
    path: /var/lib/rabbitmq
  volumeClaimTemplates:
    accessModes: ["ReadWriteOnce"]
    storage: 8Gi

env:
- name: RABBITMQ_DEFAULT_USER
  value: recomind
- name: RABBITMQ_DEFAULT_PASS
  value: recomind
- name: RABBITMQ_ERLANG_COOKIE
  value: ThisIsAStrongErlangCookieValue123

service:
  name: rabbitmq-svc
  type: ClusterIP
  port: 15672

ingress:
    enabled: true
    className: "nginx"
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      # التعديل هنا: نستخدم regex لالتقاط أي مسار بعد /rabbitmq
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      # هذا السطر يحل مشكلة الـ 404 عند نسيان السلاش في النهاية
      nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite ^/rabbitmq$ /rabbitmq/ permanent;
        proxy_set_header X-Forwarded-Prefix /rabbitmq;
    hosts:
      - host: api.recomind.site
        paths:
        - path: /rabbitmq(/|$)(.*)
          pathType: ImplementationSpecific

          backend:
            service:
              name: rabbitmq-svc
              port:
                number: 15672
    tls: 
      - hosts:
        - api.recomind.site
        secretName: recomind-tls-final-aks

    