nameOverride: "rabbitmq"
fullnameOverride: "rabbitmq"

StatefulSet:
  
  image:
    repo: rabbitmq:4.0-management-alpine
    port: 15672
  volumeMounts:
    path: /var/lib/rabbitmq
  volumeClaimTemplates:
    accessModes: ["ReadWriteOnce"]
    storage: 8Gi

env:
- name: RABBITMQ_DEFAULT_USER
  value: recomind
- name: RABBITMQ_DEFAULT_PASS
  value: recomind
- name: RABBITMQ_ERLANG_COOKIE
  value: ThisIsAStrongErlangCookieValue123

service:
  name: rabbitmq-svc
  type: ClusterIP
  port: 15672