---



- name: move docker-compose.yml on remote server
  copy:
    src:   docker-compose.yml
    dest: /home/BackendAdmin/docker-compose.yml
    owner: BackendAdmin
    group: BackendAdmin
    mode: '0644'