apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  labels:
    {{- include "Platform.labels" . | nindent 4 }}
    
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.http.name }}
      port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.port }}
      appProtocol: {{ .Values.service.http.protocol }}

    - name: {{ .Values.service.grpc.name }}
      port: {{ .Values.service.grpc.port }}
      targetPort: {{ .Values.service.grpc.port }}
      appProtocol: {{ .Values.service.grpc.protocol }}
      

  selector:
    {{- include "Platform.selectorLabels" . | nindent 4 }}
    {{- .Chart.Name }}-deployment
